import { readFileSync, writeFileSync } from 'fs';
import * as path from 'path';

// Get the current module's directory using Node.js path
const __dirname = path.resolve();

// Path to the extracted audio map from the old project
const extractedAudioMapPath = path.join(
  __dirname,
  '..',
  'old-nufu',
  'dictionnaire_nufi_web-main',
  'src',
  'data',
  'extracted_audio_map.json'
);

// Path to the output audio mapping file
const outputPath = path.join(
  __dirname,
  '..',
  'src',
  'data',
  'audioMapping.ts'
);

// Read the extracted audio map
console.log(`Reading audio map from: ${extractedAudioMapPath}`);
const extractedMap = JSON.parse(readFileSync(extractedAudioMapPath, 'utf-8'));

// Generate the TypeScript file content
let tsContent = `/**
 * Audio mapping for the Nufi dictionary
 * This file maps dictionary words to their corresponding audio filenames
 * 
 * This file is auto-generated by scripts/update-audio-mapping.ts
 * Do not edit this file directly. Instead, update the extracted_audio_map.json file
 * and regenerate this file.
 */

// Audio mapping from dictionary words to audio filenames (without .mp3 extension)
export const audioMapping: Record<string, string> = {
`;

// Add each mapping entry
const entries = Object.entries(extractedMap);
entries.sort(([a], [b]) => a.localeCompare(b));

for (const [word, filename] of entries) {
  // Escape any special characters in the word
  const escapedWord = word
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
  
  tsContent += `  "${escapedWord}": "${filename}",\n`;
}

tsContent += `};

/**
 * Get the audio filename for a dictionary word
 * @param word The dictionary word
 * @returns The audio filename without extension, or null if not found
 */
export function getAudioFilename(word: string): string | null {
  if (!word) return null;
  
  // Clean the word (convert to lowercase, trim, etc.)
  const cleanedWord = word.toLowerCase().trim();
  
  // First try exact match
  if (audioMapping[cleanedWord]) {
    return audioMapping[cleanedWord];
  }
  
  // Try to find a close match (case-insensitive)
  const normalizedWord = cleanedWord.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  
  for (const [key, value] of Object.entries(audioMapping)) {
    const normalizedKey = key.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    if (normalizedKey === normalizedWord) {
      return value as string;
    }
  }
  
  return null;
}

/**
 * Get the full audio URL for a dictionary word
 * @param word The dictionary word
 * @returns The full audio URL, or null if not found
 */
export function getAudioUrl(word: string): string | null {
  const filename = getAudioFilename(word);
  if (!filename) return null;
  
  return \`/api/audio/\${encodeURIComponent(word)}\`;
}

/**
 * Check if a dictionary word has audio
 * @param word The dictionary word
 * @returns True if the word has audio, false otherwise
 */
export function hasAudio(word: string): boolean {
  return getAudioFilename(word) !== null;
}
`;

// Write the TypeScript file
console.log(`Writing audio mapping to: ${outputPath}`);
writeFileSync(outputPath, tsContent, 'utf-8');

console.log(`Successfully updated audio mapping with ${entries.length} entries.`);
